org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Xss8m
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
cloudinaryCloudName=dlwswajln
cloudinaryUploadPreset=JosephDev_Uploads
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
